14.0 netaddiction custom
saydigital/netaddiction_addons pull request #129
Opened 2021-09-28 12:57 UTC by FabioNetaddiction

Limiti di vendita (da completare), notifiche email, immagini prodotti su categorie, creazione di 2 nuovi moduli, fix label prodotti e fix css generici

2021-09-28 13:55 UTC, warp10 requested changes

2021-09-28 13:55 UTC, warp10 commented on netaddiction_enhancement/models/website.py
> +class NetaddictionEnhancement(models.Model):
Non dovendo storare cose sul db, ed essendo invocate da un cron, sarebbe bene usare un TransientModel. Inoltre, sarebbe meglio dare un nome più pertinente alla classe. Qualcosa tipo "netaddiction.website.preorder"

2021-09-28 13:55 UTC, warp10 commented on netaddiction_enhancement/models/website.py
> +        for product in products:
Ciclare i prodotti e settare il valore su tutti richiederebbe migliaia di query. Fai
`product.inventory_availability = 'always'`
per fare una query sola e rendere l'esecuzione molto più veloce

2021-09-28 13:55 UTC, warp10 commented on netaddiction_products/models/product.py
> +            #import pdb;pdb.set_trace()
Da togliere

2021-09-28 13:55 UTC, warp10 commented on netaddiction_theme_rewrite/model/netaddiction_theme_rewrite.py
> +            if prod.id > 9:
No, questo non mi piace. Queste cose sono tremendamente error-prone.
Cos'hanno i primi 8 prodotti che non ti vanno bene? Possiamo individuare i prodotti in questione in un modo più mirato?

2021-09-28 13:55 UTC, warp10 commented on netaddiction_theme_rewrite/model/netaddiction_theme_rewrite.py
> +                    orders = request.env['sale.order.line'].search([('product_id', '=', prod.id)])
Questa query potrebbe essere particolarmente pesante. Puoi aggiungere un FIXME comment per ricordarci che dopo il go live vale la pena considerare l'ipotesi di salvare l'ammontare dei prodotti venduti come field sul prodotto?

2021-09-28 13:55 UTC, warp10 commented on netaddiction_enhancement/__manifest__.py
> +    "name": "Netaddiction Enhancement",
Visto che gli enhancement di questo modulo riguardano esclusivamente la parte website e dintorni (ma non il tema), lascerei il nome "netaddiction_website", in modo da rendere più comprensibile qual è lo scopo del modulo

2021-09-28 13:55 UTC, warp10 commented on netaddiction_enhancement/template/mail/affiliate_reject_mail.html
> +<table border="0" cellpadding="0" cellspacing="0" style="padding-top:16px; padding-bottom:16px;background-color: #F1F1F1; font-family:Verdana, Arial,sans-serif; color: #454748; width: 100%; border-co
Non ho capito cosa sono e dove vengono usati questi file in template/mail/. Se, come presumo, sono i template delle mail che devono essere inviate agli utenti, devono essere creati come record di mail.template, in modo che possano essere modificati senza dover modificare il repo. Puoi prendere ad esempio i template in netaddiction_special_offers/data/mail_template.xml

2021-09-28 13:58 UTC, FabioNetaddiction commented on netaddiction_theme_rewrite/model/netaddiction_theme_rewrite.py
> +            if prod.id > 9:
sono tutti i vecchi corrieri ecc.. non sono prodotti

2021-09-28 15:24 UTC, MatteoNet commented on netaddiction_enhancement/template/mail/affiliate_reject_mail.html
> +<table border="0" cellpadding="0" cellspacing="0" style="padding-top:16px; padding-bottom:16px;background-color: #F1F1F1; font-family:Verdana, Arial,sans-serif; color: #454748; width: 100%; border-co
Ho fatto questa cartella perche' non voglio fare l'override dei template stock di odoo / dei moduli di terze parti. ma voglio inserirli a mano. Non importa che non vengono aggiornati nel repo.

2021-09-28 16:01 UTC, warp10 commented on netaddiction_enhancement/template/mail/affiliate_reject_mail.html
> +<table border="0" cellpadding="0" cellspacing="0" style="padding-top:16px; padding-bottom:16px;background-color: #F1F1F1; font-family:Verdana, Arial,sans-serif; color: #454748; width: 100%; border-co
No, non devi fare l'override dei mail.template standard. Devi crearne di nuovi. Poi potremo associare il template che vogliamo usare ad ogni oggetto che ci serve.

2021-09-28 20:35 UTC, warp10 requested changes

2021-09-28 20:35 UTC, warp10 commented on netaddiction_theme_rewrite/model/netaddiction_theme_rewrite.py
> +            if prod.id > 9:
In tal caso filtrali usando il campo type. I veri prodotti sono di tipo "Prodotto immagazzinabile", gli altri sono prodotti di tipo "Servizio". Non è sano usare l'ID per distinguerli

2021-09-29 08:45 UTC, warp10 approved these changes

2021-09-29 08:45 UTC, merged