14.0 fix no result
saydigital/netaddiction_addons pull request #270
Opened 2021-11-05 12:38 UTC by FabioNetaddiction

aggiunto menu collassabile in tutto il sito e pagine prodotti non trovati

2021-11-05 13:09 UTC, OpenCode commented on advance_website_all_in_one/static/src/js/custom.js
> +				alert("Inserisci un numro valido di punti")
"Numero"

2021-11-05 13:09 UTC, OpenCode commented on advance_website_all_in_one/static/src/js/custom.js
> +				alert("Inserisci un numro valido di punti")
"Numero"

2021-11-05 13:09 UTC, OpenCode commented on theme_clarico_vega/templates/netaddiction_customization.xml
> +                                <t t-set="categories" t-value="request.env['product.public.category'].sudo().search([('parent_id','=',1)])" />
@FabioNetaddiction Aiutami a venirti incontro. C'è un modo in cui io posso farmi capire quando dico che le ricerche con valori fissi e legati al sistema NON DEVONO essere fatte? Non so davvero più come evidenziare la cosa. Una volta può pure passare per urgenza ma qui ci portiamo debito tecnico in una maniera davvero inutile. Possiamo farla fatta bene questa cosa? Abbiamo già molto codice "brutto" ereditato. Cerchiamo di fare in modo che il nuovo sia un pelino meglio, per favore.

2021-11-05 13:12 UTC, warp10 requested changes

2021-11-05 13:12 UTC, warp10 commented on theme_clarico_vega/templates/netaddiction_customization.xml
> +                                <t t-set="categories" t-value="request.env['product.public.category'].sudo().search([('parent_id','=',1)])" />
Provo a ribadirlo in maniera più chiara: "ovunque tu sia, qualsiasi sia il problema, qualunque sia il task, qualsiasi sia la necessità, accedere a record tramite ID (o tramite nome) non si fa, mai, per nessuna ragione, cascasse il mondo, a tutti i costi".

2021-11-05 13:12 UTC, warp10 commented on theme_clarico_vega/templates/netaddiction_customization.xml
> +                                <t t-set="category" t-value="request.env['product.public.category'].sudo().search([('id','=',1)])"/>
Repetita juvant: "ovunque tu sia, qualsiasi sia il problema, qualunque sia il task, qualsiasi sia la necessità, accedere a record tramite ID (o tramite nome) non si fa, mai, per nessuna ragione, cascasse il mondo, a tutti i costi".

2021-11-05 13:12 UTC, warp10 commented on theme_clarico_vega/templates/netaddiction_customization.xml
> +                                <t t-set="categories" t-value="request.env['product.public.category'].sudo().search([('parent_id','=',1)])" />
Repetita juvant #2: Provo a ribadirlo in maniera più chiara: "ovunque tu sia, qualsiasi sia il problema, qualunque sia il task, qualsiasi sia la necessità, accedere a record tramite ID (o tramite nome) non si fa, mai, per nessuna ragione, cascasse il mondo, a tutti i costi".

2021-11-05 13:12 UTC, warp10 commented on theme_clarico_vega/templates/netaddiction_customization.xml
> +                                <t t-set="category" t-value="request.env['product.public.category'].sudo().search([('id','=',1)])"/>
Repetita juvant #3: Provo a ribadirlo in maniera più chiara: "ovunque tu sia, qualsiasi sia il problema, qualunque sia il task, qualsiasi sia la necessità, accedere a record tramite ID (o tramite nome) non si fa, mai, per nessuna ragione, cascasse il mondo, a tutti i costi".

2021-11-05 13:12 UTC, warp10 commented on theme_clarico_vega/templates/netaddiction_customization.xml
> +                                   t-value="request.env['product.public.category'].sudo().search([('id', '=', c)])"/>
Conviene fare browse() piuttosto che search()

2021-11-05 13:13 UTC, OpenCode commented on theme_clarico_vega/templates/netaddiction_customization.xml
> +                                <t t-set="category" t-value="request.env['product.public.category'].sudo().search([('id','=',1)])"/>
Anche qua. Inoltre qui il problema è doppio perché se hai l'ID tanto vale far la browse.

2021-11-05 13:13 UTC, OpenCode commented on theme_clarico_vega/templates/netaddiction_customization.xml
> +                                <t t-set="categories" t-value="request.env['product.public.category'].sudo().search([('parent_id','=',1)])" />
Come sopra

2021-11-05 13:13 UTC, OpenCode commented on theme_clarico_vega/templates/netaddiction_customization.xml
> +                                <t t-set="category" t-value="request.env['product.public.category'].sudo().search([('id','=',1)])"/>
Come sopra

2021-11-05 13:13 UTC, OpenCode commented on theme_clarico_vega/templates/netaddiction_customization.xml
> +                                   t-value="request.env['product.public.category'].sudo().search([('id', '=', c)])"/>
Come sopra

2021-11-08 10:31 UTC, warp10 approved these changes

2021-11-08 10:32 UTC, merged