14.0 fix wallet payment
saydigital/netaddiction_addons pull request #309
Opened 2021-11-23 14:31 UTC by FabioNetaddiction

modificato il funzionamento del wallet, mandatelo in test poi in seguito termineremo la parte layout della lista transazioni

2021-11-24 14:56 UTC, warp10 requested changes
A parte i commenti, vedo 4 submodule aggiunti al repo, ma non vedo modifiche al file .gitmodules

2021-11-24 14:56 UTC, warp10 commented on netaddiction_payments/controllers/main.py
> +        odoo_wallet = request.env["ir.module.module"].sudo().search([("name", "=", "odoo_website_wallet")])
Questa ricerca non verifica che i moduli siano installati, verifica solo che siano registrati nel database. Il controllo successivo dello stato del modulo implica solo fare una query inutile sul db ogni volta che questo metodo viene acceduto. Piuttosto, aggiungili tra le dipendenze del modulo se vuoi avere la certezza che siano presenti e correttamente installati, e non ci sarà bisogno di fare altri check

2021-11-24 14:56 UTC, warp10 commented on netaddiction_payments/controllers/main.py
> +        partner = request.env["res.partner"].search([("id", "=", order.partner_id.id)])
Ok che è indiano, ma evitiamo di fare una query su una tabella da 2M di record quando hai l'oggetto che t iserve già su order.partner_id

2021-11-25 09:31 UTC, UNF0RGIV3N3 commented
@warp10 Risolto, avevo dimenticato di aggiungere i submodules, scusatemi.

2021-11-25 09:32 UTC, MatteoNet commented
@warp10 Risolto, scusatemi ma avevo dimenticato di aggiungere i submodules.

2021-11-29 10:10 UTC, warp10 approved these changes

2021-11-29 10:10 UTC, merged