aggiunta pagina dei tag
saydigital/netaddiction_addons pull request #72
Opened 2021-07-19 10:24 UTC by FabioNetaddiction

inserite le etichette dei tag nei prodotti, creata la pagina per mostrare i tag: BASE URL / tag / <nome tag>

2021-07-20 15:47 UTC, OpenCode requested changes

2021-07-20 15:47 UTC, OpenCode commented on netaddiction_theme_rewrite/model/netaddiction_theme_rewrite.py
> +            query = f"SELECT id FROM product_template_tag WHERE name ='{tag_name}'"
Siccome il tag arriva dall'url chiamante, non bisogna in nessunissimo caso usare una query cruda. Passare dall'ORM dovrebbe essere la pratica giusta.

2021-07-21 08:20 UTC, warp10 requested changes

2021-07-21 08:20 UTC, warp10 commented on netaddiction_theme_rewrite/model/netaddiction_theme_rewrite.py
> +            query = f"SELECT id FROM product_template_tag WHERE name ='{tag_name}'"
Condivido, il dato non è neanche sanitizzato ed espone un rischio di sicurezza. E' indispensabile cambiare questa query e usare l'ORM

2021-07-21 08:20 UTC, warp10 commented on netaddiction_theme_rewrite/model/netaddiction_theme_rewrite.py
> +        try:
Idem qui, meglio usare l'ORM

2021-08-04 07:19 UTC, warp10 approved these changes

2021-08-04 08:32 UTC, OpenCode approved these changes

2021-08-04 12:55 UTC, merged